#!/bin/bash

echo "This script might run into error if some of packages in [zip,curl,openssh,neovim,python,node,npm] are not installed"

echo "Installing VimPlug..."
sh -c 'curl -s -fLo ~/.vim/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
echo "Done"

echo "Copying init.vim ..."
cp -fv ./vimrc ~/.vimrc
echo "Done"

echo "Download and install OMZ: ..."
bash -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
